### ISSUE TITLE
Unable to run jest test

### ISSUE THREAD

**Issue by marcschregardus** [3wks/generator-thundr-gae-react#3]
The jest test won't run when starting the app up - or running independently (the only way I could get the app to start was to delete the `index.test.js` file altogether).

I'm using Node v8.8.0 and NPM v5.4.2 on Mac OS Sierra 10.12.6

**Comment by kuhnza** [comment]
Looks like the jest roots config in `package.json` was still pointing at static rather than client where the frontend code now resides.
